### ISSUE TITLE
Tests fail with `AttributeError` and `ModuleNotFoundError` on different versions.

### ISSUE THREAD

**Issue by TheChymera** [asdf-format/asdf#1319]
Here is [the build log for `2.14.3`](https://ppb.chymera.eu/6e1ed7.log), with the following error traceback excerpt:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1690, in parse_warning_filter
    category: Type[Warning] = _resolve_warning_category(category_)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1728, in _resolve_warning_category
    m = __import__(module, None, None, [klass])
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/__init__.py", line 24, in <module>
    from ._convenience import info
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/_convenience.py", line 8, in <module>
    from ._display import DEFAULT_MAX_COLS, DEFAULT_MAX_ROWS, DEFAULT_SHOW_VALUES, render_tree
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/_display.py", line 12, in <module>
    from ._node_info import create_tree
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/_node_info.py", line 4, in <module>
    from .schema import load_schema
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/schema.py", line 17, in <module>
    from .config import get_config
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/config.py", line 9, in <module>
    from . import entry_points, util, versioning
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/entry_points.py", line 12, in <module>
    from .resource import ResourceMappingProxy
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/var/tmp/portage/dev-python/asdf-2.14.3/work/asdf-2.14.3/asdf/resource.py", line 8, in <module>
    from asdf_standard import DirectoryResourceMapping as _DirectoryResourceMapping
ModuleNotFoundError: No module named 'asdf_standard'
```

Is this a missing external dependency?

A different error [occurs with `2.8.3`](https://ppb.chymera.eu/07837e.log)):

This is the excerpt of the error traceback from the log:

```
python3.10 -m pytest -vv -ra -l -Wdefault --color=yes -o console_output_style=count -p no:cov -p no:flake8 -p no:flakes -p no:pylint -p no:markdown -p no:sugar -p no:xvfb -p no:tavern asdf/tests
ImportError while loading conftest '/var/tmp/portage/dev-python/asdf-2.8.3/work/asdf-2.8.3/asdf/conftest.py'.
asdf/conftest.py:8: in <module>
    from asdf.tests.httpserver import HTTPServer, RangeHTTPServer
asdf/tests/__init__.py:8: in <module>
    from .helpers import get_test_data_path
asdf/tests/helpers.py:8: in <module>
    from astropy.coordinates import ICRS
/usr/lib/python3.10/site-packages/astropy/coordinates/__init__.py:10: in <module>
    from .angles import *
/usr/lib/python3.10/site-packages/astropy/coordinates/angles.py:14: in <module>
    from . import angle_formats as form
/usr/lib/python3.10/site-packages/astropy/coordinates/angle_formats.py:30: in <module>
    from astropy import units as u
/usr/lib/python3.10/site-packages/astropy/units/__init__.py:17: in <module>
    from .quantity import *
/usr/lib/python3.10/site-packages/astropy/units/quantity.py:32: in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
/usr/lib/python3.10/site-packages/astropy/units/quantity_helper/__init__.py:10: in <module>
    from . import helpers, function_helpers
/usr/lib/python3.10/site-packages/astropy/units/quantity_helper/function_helpers.py:116: in <module>
    np.asscalar, np.alen,
/usr/lib/python3.10/site-packages/numpy/__init__.py:284: in __getattr__
    raise AttributeError("module {!r} has no attribute "
E   AttributeError: module 'numpy' has no attribute 'asscalar'. Did you mean: 'isscalar'?
```

This one is similar to [another issue](https://github.com/spacetelescope/gwcs/issues/437) I ran into recently... is this a problem with newer numpy versions having dropped `asscalar`?

**Comment by WilliamJamieson** [comment]
To address your first question, since ASDF 2.10, ASDF stopped bundling the asdf-standard package. This means that asdf-standard is a required dependency as stated in the pyproject.toml file.

As for your second question, we dropped support for ASDF 2.8 awhile ago, and this appears to be a result of you using a too new version of numpy with that version of ASDF.

**Comment by WilliamJamieson** [comment]
Please include a full pip freeze.

**Comment by nden** [comment]
@TheChymera Do you think this is still a problem? Also this [gwcs issue](https://github.com/spacetelescope/gwcs/issues/437) which I can't reproduce.

**Comment by braingram** [comment]
@TheChymera Feel free to reopen this if you're still having the issue. Happy to help!
