### ISSUE TITLE
readthedocs failed on release

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1844]
https://readthedocs.org/projects/asdf/builds/25818935/
failed on `towncrier` with the error:
```
Loading template...
Finding news fragments...
Rendering news fragments...
Writing to newsfile...
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/bin/towncrier", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/towncrier/build.py", line 123, in _main
    return __main(
           ^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/towncrier/build.py", line 263, in __main
    append_to_newsfile(
  File "/home/docs/checkouts/readthedocs.org/user_builds/asdf/conda/3.5.0/lib/python3.11/site-packages/towncrier/_writer.py", line 53, in append_to_newsfile
    raise ValueError("It seems you've already produced newsfiles for this version?")
ValueError: It seems you've already produced newsfiles for this version?
```

**Comment by braingram** [comment]
I pushed a hot fix https://github.com/asdf-format/asdf/commit/4de5de77ad01689470f4c2ddb2c056e2c0bdea19 and retagged to move forward with the release but it would be good to sort out what's going on. Pinging @zacharyburnett but at the moment there's nothing urgent.

**Comment by zacharyburnett** [comment]
I think that `|| true` is a good workaround here, as the issue only exists on the exact release commit
